### ISSUE TITLE
less 8

### ISSUE THREAD

**Issue by GetTurnedOn** [scotchfield/party-party-party#1]
less radius, and this is HPV party
const partyRadius = 8;

**Comment by scotchfield** [comment]
Sorry, I'm not sure I understand. Are you suggesting to change the default radius? You should be able to change this easily in the code. Maybe this should be a command line argument though.

Thanks for the feedback! :)

**Comment by somewhatabstract** [comment]
I added the `radius` arg here, https://github.com/scotchfield/party-party-party/pull/2.
